'''
remove.py
This Python script contains all the function to unsibcribe from the community and remove the docker-machine
/!\ Please, do not edit this file /!\
'''

import common
import restcall
import subprocess

def main(username=None, password=None):
    if username == None and password == None:
        (result, logs) = restcall.log_in(3)[1]
        if not result:
            sys.exit(1)
    else:
        logs = (username, password)

    if restcall.remove_worker(logs):
        cmd = "docker-machine rm -y " + common.DOCKER_MACHINE_NAME
        try:
            subprocess.check_output(cmd.split()).split('\n')
            print "Docker-machine removed."
        except Exception :
            print "No docker-machine to remove."

if __name__ == "__main__":
    main()
