'''
restcall.py
This Python script contains all the function to call the cocass rest API
/!\ Please, do not edit this file /!\
'''

import common
import requests

def create_user((user, password)):
    url = common.SERVER_URL + "User/new/"  + user + "/" + password
    r = requests.post(url)
    return r.status_code == common.CODE_SUCCESS


# User logging to the website
# @param attempts : The number of logging attempts
# @return : True or False, accordig to the success of the logging
def log_in(attempts):
t = attempts
while t > 0:
if not api_log_in(get_logs()):
    t -= 1
    print "Log in failed. Attempts remaining : " + str(t)
else:
    print "Login successfull."
    return True
return False

def api_log_in((user, password)):
    # TODO
    return True

def send_config(config):
    # TODO
    return True
