'''
restcall.py
This Python script contains all the function to call the cocass rest API
/!\ Please, do not edit this file /!\
'''

import common
import requests

def create_user((user, password)):
    url = common.SERVER_URL + "User/new/"  + user + "/" + password
    r = requests.post(url)
    return r.status_code == common.CODE_SUCCESS

def log_in((user, password)):
    # TODO
    return True

def send_config(config):
    # TODO
    return True
